export enum Assets {
  BgIntroDesktop = 'assets/imgs/bg-intro-desktop.svg',
  BgIntroMobile = '../../assets/imgs/bg-intro-mobile.svg',
  Favicon = '../../assets/imgs/favicon-32x32.png',
  IconApi = '../../assets/imgs/icon-api.svg',
  IconBudgeting = '../../assets/imgs/icon-budgeting.svg',
  IconClose = '../../assets/imgs/icon-close.svg',
  IconFacebook = '../../assets/imgs/icon-facebook.svg',
  IconHamburger = '../../assets/imgs/icon-hamburger.svg',
  IconInstagram = '../../assets/imgs/icon-instagram.svg',
  IconOnboarding = '../../assets/imgs/icon-onboarding.svg',
  IconOnline = '../../assets/imgs/icon-online.svg',
  IconPinterest = '../../assets/imgs/icon-pinterest.svg',
  IconTwitter = '../../assets/imgs/icon-twitter.svg',
  IconYoutube = '../../assets/imgs/icon-youtube.svg',
  ImageConfetti = '../../assets/imgs/image-confetti.jpg',
  ImageCurrency = '../../assets/imgs/image-currency.jpg',
  ImageMockups = '../../assets/imgs/image-mockups.png',
  ImagePlane = '../../assets/imgs/image-plane.jpg',
  ImageRestaurant = '../../assets/imgs/image-restaurant.jpg',
  Logo = '../../assets/imgs/logo.svg',
}
